### PR TITLE
Initial Specification

### PR DESCRIPTION
**Pull request by Murto**
The first version of the specification. Left broad and uncomplicated to allow us some creative freedom in our implementation. Not meant to be comprehensive, instead it is a brief guideline of functionality and a definition of scope.

### CODE REVIEW

**Comment by SinanVanli** [comment]
I really admire the effort you put into this. Hopefully it sets a bar for the quality of the entire product. My only issue is having the Character Select screen from the main menu and not from the select game menu. For example WoW's character select and create character screens are both after the choose server screen. Obviously this is somewhat different. I suppose different games/people will prefer different ways. Perhaps we could keep this in mind when developing and experiment with the two ways. I expect there to be a sweet spot between the two with "favourite" characters etc.

**Comment by SinanVanli** [comment]
I'm also really glad to see how much SE and SDP have helped.

**Comment by Murto** [comment]
When creating the outline I was thinking that filtering could be added on top of the Select Character form as a bonus later. Sorting a list of characters by game - like sorting files by file type - would make sense if we take the list approach.

**Comment by Murto** [comment]
I've just corrected a couple of typos and reduced the figure size for this commit.

**Comment by Murto** [comment]
I agree with the experimentation in general. I'm sure we will come back to the spec and make changes along the way.

**Pull request merged**
